repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        verbose: true
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
    -   id: prettier
        files: \.[jt]sx?$
-   repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
    -   id: stylelint
        args: [--fix]
        additional_dependencies:
            - stylelint@13.11.0
            - stylelint-config-standard@20.0.0

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.46.0
    hooks:
    -   id: eslint
        args: [--fix --silent]
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
            - eslint@7.21.0
            - eslint-config-react-app
