version: 1
filters:
  correlation_id:
    (): asgi_correlation_id.CorrelationIdFilter
    uuid_length: 32
formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    filters: [correlation_id]
    formatter: json
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    filters: [correlation_id]
    formatter: json
    filename: backend.log
    mode: a
root:
  level: DEBUG
  handlers: [console, file]
  propagate: yes

loggers:
  uvicorn:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  uvicorn.access:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  uvicorn.error:
    level: DEBUG
    handlers: [console, file]
    propagate: no
